# Run with:
# docker-compose -f .\Docker-compose.prod.yml build
# docker-compose -f .\Docker-compose.prod.yml up
version: "3"

services:
  server-service:
    build: "./server"
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REACT_APP_SERVER_PORT=80
      - GITLAB_TOKEN=${GITLAB_TOKEN}
      - GITLAB_URL=${GITLAB_URL}
    depends_on:
      - "database-service"
    ports:
      - "${REACT_APP_SERVER_PORT}:80"
  database-service:
    image: "postgres:10"
    volumes:
      - "database-data:/var/lib/postgresql/data"
volumes:
  database-data: